'use strict';

// Only the disposable Actions checkout is modified. The desktop editor still
// needs its local dependency, so never run this against the working blog.
const fs = require('node:fs');
const path = require('node:path');
const { isIP } = require('node:net');

if (process.env.GITHUB_ACTIONS !== 'true') {
  throw new Error('This helper only runs in a disposable GitHub Actions checkout.');
}

const rawUrl = process.env.BLOG_URL?.trim();
if (!rawUrl) {
  throw new Error('Set the BLOG_URL repository variable to the public blog URL, e.g. https://blog.example.com/.');
}
let url;
try { url = new URL(rawUrl); }
catch { throw new Error('BLOG_URL must be a complete public HTTPS URL.'); }
const hostname = url.hostname.replace(/^\[|\]$/g, '');
if (url.protocol !== 'https:' || url.username || url.password || url.search || url.hash
    || !hostname.includes('.') || isIP(hostname) || /(?:^|\.)(?:localhost|local|internal)$/.test(hostname)) {
  throw new Error('BLOG_URL must use the public HTTPS domain of this site, without credentials, a query or a fragment.');
}
url.pathname = url.pathname.replace(/\/*$/, '/');

const pkgPath = path.resolve('package.json');
const lockPath = path.resolve('package-lock.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'));
if (!lock.packages?.['']) throw new Error('Commit a package-lock.json generated by npm 7 or newer.');
const dependencySections = ['dependencies', 'devDependencies', 'optionalDependencies'];

// Hexo Pro is an editing service, not a renderer. Its file:../ dependency
// cannot be installed by GitHub and is unnecessary for generating the site.
const editorLink = lock.packages['node_modules/hexo-pro'];
const editorLocation = editorLink?.link ? editorLink.resolved : null;
for (const section of dependencySections) {
  if (pkg[section]) delete pkg[section]['hexo-pro'];
  if (lock.packages[''][section]) delete lock.packages[''][section]['hexo-pro'];
}
delete lock.packages['node_modules/hexo-pro'];
if (lock.dependencies) delete lock.dependencies['hexo-pro'];
const remainingLinks = new Set(Object.values(lock.packages)
  .filter(entry => entry.link)
  .map(entry => entry.resolved));
for (const [location, entry] of Object.entries(lock.packages)) {
  // npm may retain metadata for earlier locations of a moved local checkout.
  // Once no installed link points there, this metadata is no longer a dependency.
  if (location.startsWith('../') && (location === editorLocation || entry.name === 'hexo-pro' || !remainingLinks.has(location))) {
    delete lock.packages[location];
  }
}

// Fail explicitly if another dependency still relies on a developer's machine.
for (const section of dependencySections) {
  for (const [name, spec] of Object.entries(pkg[section] || {})) {
    if (/^(?:file:)?(?:\.\.\/|\/|[a-z]:[\\/])/i.test(spec)) {
      throw new Error(`Dependency ${name} points outside the repository. Use a published version or include it in the repository.`);
    }
  }
}
for (const location of Object.keys(lock.packages)) {
  if (location.startsWith('../')) throw new Error('package-lock.json contains another dependency outside the repository.');
}

fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
fs.writeFileSync(lockPath, JSON.stringify(lock, null, 2) + '\n');
// JSON is also valid YAML. This overrides the URL for this build only.
fs.writeFileSync('_config.ci.yml', JSON.stringify({
  url: url.href,
  root: url.pathname,
  public_dir: 'public',
  render_drafts: false,
  deploy: []
}, null, 2) + '\n');
console.log('Cloud build prepared. Published pages use ' + url.href);
